"""
===========================================================
Development of a Digital Twin-Based Predictive Maintenance
System for Industrial Motors

Bachelor of Engineering Final Year Project

Institution:
Thakur College of Engineering and Technology (TCET)

Department:
Internet of Things (IoT)

Academic Year:
2025–2026

Authors:
- Keyur Chauhan
- Shivangi Chouhan
- Arshiya Khan

Guide:
Ms. Ekta Desai

Description:
Flask backend responsible for receiving sensor readings,
executing the Machine Learning pipeline, and returning
real-time predictive maintenance insights.

Note:
This repository contains the primary implementation of the
project. Some auxiliary scripts and development utilities
have been omitted to keep the repository concise.
===========================================================
"""

from flask import Flask, jsonify, request
from flask_cors import CORS

from machine_learning.ml_pipeline import (
    load_all_data,
    compute_features,
    train_anomaly_detector,
    train_fault_classifier,
    RealTimePredictor
)

# ---------------------------------------------------------
# Flask Configuration
# ---------------------------------------------------------

app = Flask(__name__)
CORS(app)

print("=" * 60)
print(" Digital Twin Backend Initializing ")
print("=" * 60)

# ---------------------------------------------------------
# Model Initialization
# ---------------------------------------------------------

print("[INFO] Loading datasets...")

healthy_df, full_df = load_all_data()

print("[INFO] Extracting statistical features...")

healthy_features = compute_features(
    healthy_df,
    window_size=20
)

full_features = compute_features(
    full_df,
    window_size=20
)

healthy_only = healthy_features[
    healthy_features["fault_label"] == 0
].copy()

print("[INFO] Training Isolation Forest...")

isolation_model, scaler, anomaly_columns = train_anomaly_detector(
    healthy_only
)

print("[INFO] Training Fault Classifier...")

classifier, classifier_columns = train_fault_classifier(
    full_features
)

print("[INFO] Creating Real-Time Predictor...")

predictor = RealTimePredictor(
    isolation_model,
    scaler,
    classifier,
    anomaly_columns,
    classifier_columns
)

print("Backend initialized successfully.\n")

# ---------------------------------------------------------
# API Routes
# ---------------------------------------------------------


@app.route("/ingest", methods=["POST"])
def ingest():
    """
    Receive live sensor data from ESP32 or CSV Streamer.
    """

    data = request.get_json()

    predictor.add_reading(
        timestamp_ms=data["timestamp_ms"],
        ax=data["ax"],
        ay=data["ay"],
        az=data["az"],
        temp=data["temp"],
        hum=data["humidity"],
        rpm=data.get("rpm", 400)
    )

    return jsonify({
        "status": "success",
        "message": "Sensor reading received."
    })


@app.route("/predict", methods=["GET"])
def predict():
    """
    Return the latest prediction generated by
    the Machine Learning pipeline.
    """

    prediction = predictor.get_ui_output()

    if prediction is None:

        return jsonify({
            "status": "buffering",
            "message": "Waiting for 20 sensor readings..."
        })

    return jsonify(prediction)


@app.route("/status", methods=["GET"])
def status():
    """
    Backend health check endpoint.
    """

    return jsonify({

        "status": "online",

        "backend": "Flask",

        "ml_models": "Isolation Forest + XGBoost + Rule Engine"

    })


@app.route("/reset", methods=["POST"])
def reset():
    """
    Reset prediction buffer.
    """

    global predictor

    predictor = RealTimePredictor(
        isolation_model,
        scaler,
        classifier,
        anomaly_columns,
        classifier_columns
    )

    return jsonify({

        "status": "success",

        "message": "Predictor state reset."

    })


# ---------------------------------------------------------
# Application Entry Point
# ---------------------------------------------------------

if __name__ == "__main__":

    print("[INFO] Starting Flask Server...")

    app.run(

        host="0.0.0.0",

        port=5000,

        debug=False

    )